/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShanhaijingRouteImport } from './routes/shanhaijing'
import { Route as DaojiaRouteImport } from './routes/daojia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShanhaijingIndexRouteImport } from './routes/shanhaijing.index'
import { Route as DaojiaIndexRouteImport } from './routes/daojia.index'
import { Route as ShanhaijingSlugRouteImport } from './routes/shanhaijing.$slug'
import { Route as DaojiaSlugRouteImport } from './routes/daojia.$slug'

const ShanhaijingRoute = ShanhaijingRouteImport.update({
  id: '/shanhaijing',
  path: '/shanhaijing',
  getParentRoute: () => rootRouteImport,
} as any)
const DaojiaRoute = DaojiaRouteImport.update({
  id: '/daojia',
  path: '/daojia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShanhaijingIndexRoute = ShanhaijingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShanhaijingRoute,
} as any)
const DaojiaIndexRoute = DaojiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DaojiaRoute,
} as any)
const ShanhaijingSlugRoute = ShanhaijingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShanhaijingRoute,
} as any)
const DaojiaSlugRoute = DaojiaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DaojiaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daojia': typeof DaojiaRouteWithChildren
  '/shanhaijing': typeof ShanhaijingRouteWithChildren
  '/daojia/$slug': typeof DaojiaSlugRoute
  '/shanhaijing/$slug': typeof ShanhaijingSlugRoute
  '/daojia/': typeof DaojiaIndexRoute
  '/shanhaijing/': typeof ShanhaijingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daojia/$slug': typeof DaojiaSlugRoute
  '/shanhaijing/$slug': typeof ShanhaijingSlugRoute
  '/daojia': typeof DaojiaIndexRoute
  '/shanhaijing': typeof ShanhaijingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daojia': typeof DaojiaRouteWithChildren
  '/shanhaijing': typeof ShanhaijingRouteWithChildren
  '/daojia/$slug': typeof DaojiaSlugRoute
  '/shanhaijing/$slug': typeof ShanhaijingSlugRoute
  '/daojia/': typeof DaojiaIndexRoute
  '/shanhaijing/': typeof ShanhaijingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daojia'
    | '/shanhaijing'
    | '/daojia/$slug'
    | '/shanhaijing/$slug'
    | '/daojia/'
    | '/shanhaijing/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daojia/$slug' | '/shanhaijing/$slug' | '/daojia' | '/shanhaijing'
  id:
    | '__root__'
    | '/'
    | '/daojia'
    | '/shanhaijing'
    | '/daojia/$slug'
    | '/shanhaijing/$slug'
    | '/daojia/'
    | '/shanhaijing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaojiaRoute: typeof DaojiaRouteWithChildren
  ShanhaijingRoute: typeof ShanhaijingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shanhaijing': {
      id: '/shanhaijing'
      path: '/shanhaijing'
      fullPath: '/shanhaijing'
      preLoaderRoute: typeof ShanhaijingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daojia': {
      id: '/daojia'
      path: '/daojia'
      fullPath: '/daojia'
      preLoaderRoute: typeof DaojiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shanhaijing/': {
      id: '/shanhaijing/'
      path: '/'
      fullPath: '/shanhaijing/'
      preLoaderRoute: typeof ShanhaijingIndexRouteImport
      parentRoute: typeof ShanhaijingRoute
    }
    '/daojia/': {
      id: '/daojia/'
      path: '/'
      fullPath: '/daojia/'
      preLoaderRoute: typeof DaojiaIndexRouteImport
      parentRoute: typeof DaojiaRoute
    }
    '/shanhaijing/$slug': {
      id: '/shanhaijing/$slug'
      path: '/$slug'
      fullPath: '/shanhaijing/$slug'
      preLoaderRoute: typeof ShanhaijingSlugRouteImport
      parentRoute: typeof ShanhaijingRoute
    }
    '/daojia/$slug': {
      id: '/daojia/$slug'
      path: '/$slug'
      fullPath: '/daojia/$slug'
      preLoaderRoute: typeof DaojiaSlugRouteImport
      parentRoute: typeof DaojiaRoute
    }
  }
}

interface DaojiaRouteChildren {
  DaojiaSlugRoute: typeof DaojiaSlugRoute
  DaojiaIndexRoute: typeof DaojiaIndexRoute
}

const DaojiaRouteChildren: DaojiaRouteChildren = {
  DaojiaSlugRoute: DaojiaSlugRoute,
  DaojiaIndexRoute: DaojiaIndexRoute,
}

const DaojiaRouteWithChildren =
  DaojiaRoute._addFileChildren(DaojiaRouteChildren)

interface ShanhaijingRouteChildren {
  ShanhaijingSlugRoute: typeof ShanhaijingSlugRoute
  ShanhaijingIndexRoute: typeof ShanhaijingIndexRoute
}

const ShanhaijingRouteChildren: ShanhaijingRouteChildren = {
  ShanhaijingSlugRoute: ShanhaijingSlugRoute,
  ShanhaijingIndexRoute: ShanhaijingIndexRoute,
}

const ShanhaijingRouteWithChildren = ShanhaijingRoute._addFileChildren(
  ShanhaijingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaojiaRoute: DaojiaRouteWithChildren,
  ShanhaijingRoute: ShanhaijingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
