/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShanhaijingRouteImport } from './routes/shanhaijing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShanhaijingIndexRouteImport } from './routes/shanhaijing.index'
import { Route as ShanhaijingSlugRouteImport } from './routes/shanhaijing.$slug'

const ShanhaijingRoute = ShanhaijingRouteImport.update({
  id: '/shanhaijing',
  path: '/shanhaijing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShanhaijingIndexRoute = ShanhaijingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShanhaijingRoute,
} as any)
const ShanhaijingSlugRoute = ShanhaijingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShanhaijingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shanhaijing': typeof ShanhaijingRouteWithChildren
  '/shanhaijing/$slug': typeof ShanhaijingSlugRoute
  '/shanhaijing/': typeof ShanhaijingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shanhaijing/$slug': typeof ShanhaijingSlugRoute
  '/shanhaijing': typeof ShanhaijingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shanhaijing': typeof ShanhaijingRouteWithChildren
  '/shanhaijing/$slug': typeof ShanhaijingSlugRoute
  '/shanhaijing/': typeof ShanhaijingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shanhaijing' | '/shanhaijing/$slug' | '/shanhaijing/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shanhaijing/$slug' | '/shanhaijing'
  id: '__root__' | '/' | '/shanhaijing' | '/shanhaijing/$slug' | '/shanhaijing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShanhaijingRoute: typeof ShanhaijingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shanhaijing': {
      id: '/shanhaijing'
      path: '/shanhaijing'
      fullPath: '/shanhaijing'
      preLoaderRoute: typeof ShanhaijingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shanhaijing/': {
      id: '/shanhaijing/'
      path: '/'
      fullPath: '/shanhaijing/'
      preLoaderRoute: typeof ShanhaijingIndexRouteImport
      parentRoute: typeof ShanhaijingRoute
    }
    '/shanhaijing/$slug': {
      id: '/shanhaijing/$slug'
      path: '/$slug'
      fullPath: '/shanhaijing/$slug'
      preLoaderRoute: typeof ShanhaijingSlugRouteImport
      parentRoute: typeof ShanhaijingRoute
    }
  }
}

interface ShanhaijingRouteChildren {
  ShanhaijingSlugRoute: typeof ShanhaijingSlugRoute
  ShanhaijingIndexRoute: typeof ShanhaijingIndexRoute
}

const ShanhaijingRouteChildren: ShanhaijingRouteChildren = {
  ShanhaijingSlugRoute: ShanhaijingSlugRoute,
  ShanhaijingIndexRoute: ShanhaijingIndexRoute,
}

const ShanhaijingRouteWithChildren = ShanhaijingRoute._addFileChildren(
  ShanhaijingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShanhaijingRoute: ShanhaijingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
